### ISSUE TITLE
Wrong value passed as prop 

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#332]
In Countries.vue, In network-search-bar wrong prop is passed ie. noAs which is of type Boolean was passed as "true" which is String.

The error in the console is : 'Invalid prop: type check failed for prop "noAS". Expected Boolean, got String with value "true".'

**Comment by Rithvik-padma** [comment]
@romain-fontugne It is a very small issue, I want to work on this. 
I have already made the required change and it got fixed in my local environment.

**Comment by kkartik07** [comment]
@Rithvik-padma I have fixed this and already made a PR

**Comment by Rithvik-padma** [comment]
@kkartik07 the PR you have made doesn't fix the issue as Interpolation in attributes was removed by Vue in v2.2 ig, maybe that is the reason the checks have not passed.
I am making a PR to fix this issue, you can check it in your local environment u will most probably get an error, so close your PR asap to avoid merge conflicts.

**Comment by kkartik07** [comment]
@Rithvik-padma On my local environment the error is fixed after i made the changes

**Comment by Rithvik-padma** [comment]
@kkartik07 maybe you are using an older version of Vue. You can checkout this forum https://forum.vuejs.org/t/interpolation-inside-attributes-deprecated-or-removed/2070.
Maybe even in the checks, you may find an error related to it

**Comment by kkartik07** [comment]
@Rithvik-padma Yes it seems fine now. I will be removing my PR
